name: Continuous Deployment

on:
  workflow_call:    # This allows the CI script to trigger this script
    inputs:
      image_tag:
        required: true
        type: string
permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
   
    steps:
      - name: Checkout k8s manifests
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::720546261973:role/githubactions # Use your Role ARN
          aws-region: ap-south-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name aqua-cluster
          echo "Handshake with EKS successful"

      - name: Update Image Tag and Deploy
        run: |
          # Injecting the image_tag passed from the CI workflow
          sed -i "s|image:.*|image: 720546261973.dkr.ecr.ap-south-1.amazonaws.com/bhimavaram-aqua:${{ inputs.image_tag }}|g" k8s/deployment.yml
          kubectl apply -f k8s/
          echo "✅ Cluster updated with version: ${{ inputs.image_tag }}"