name: Continuous Deployment

on:
  workflow_call:    # This allows the CI script to trigger this script
    inputs:
      image_tag:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout k8s manifests
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name aqua-cluster
          echo "Handshake with EKS successful"

      - name: Update Image Tag and Deploy
        run: |
          # Injecting the image_tag passed from the CI workflow
          sed -i "s|image:.*|image: 720546261973.dkr.ecr.ap-south-1.amazonaws.com/bhimavaram-aqua:${{ inputs.image_tag }}|g" k8s/deployment.yml
          kubectl apply -f k8s/
          echo "✅ Cluster updated with version: ${{ inputs.image_tag }}"