name: Continuous Integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]   # Tests the build before allowing a merge
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: bhimavaram-aqua

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    outputs:
      tag: ${{ github.sha }} # Saving this for the CD workflow
    steps:
      - uses: actions/checkout@v4

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::720546261973:role/githubactions # Use your Role ARN
          aws-region: ap-south-1

      - name: login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push
        run: |
          # INDUSTRY PRO-TIP: Only push to ECR if we are on the main branch
          # Pull requests will only test the build
          if [ "${{ github.event_name }}" == "push" ]; then
            docker build -t ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }} .
            docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}
          else
            echo "Pull Request: Testing build only..."
            docker build -t test-image .
          fi

  # THE CONNECTION POINT
  trigger-deploy:
    needs: build-and-push
    # Only call the deployment if code was merged/pushed to main
    if: always()
    uses: ./.github/workflows/cd-deploy.yml
    with:
      image_tag: ${{ needs.build-and-push.outputs.tag }}
    secrets: inherit